package com.bbl.userapi.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * In-memory user entity. Fields follow the simplified jsonplaceholder /users model.
 * Getters/setters/constructors are generated by Lombok.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {

    private Long id;
    private String name;
    private String username;
    private String email;
    private String phone;
    private String website;
}
