package com.bbl.userapi.dto;

import jakarta.validation.constraints.Email;
import lombok.Data;

/**
 * Payload for partial update (PUT) requests.
 * Every field is optional: only the fields that are present (non-null) are applied,
 * so a request can change a single field and leave the rest untouched.
 * Getters/setters are generated by Lombok.
 */
@Data
public class UserUpdateRequest {

    private String name;
    private String username;

    @Email(message = "email must be a valid email address")
    private String email;

    private String phone;
    private String website;
}
