package com.bbl.userapi.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

/**
 * Payload for create (POST) and update (PUT) requests.
 * name, username and email are mandatory; phone and website are optional.
 * Getters/setters are generated by Lombok.
 */
@Data
public class UserRequest {

    @NotBlank(message = "name is required")
    private String name;

    @NotBlank(message = "username is required")
    private String username;

    @NotBlank(message = "email is required")
    @Email(message = "email must be a valid email address")
    private String email;

    private String phone;
    private String website;
}
